'use strict';

export default {
    LOGIN_USER: 'LOGIN_USER',
    CHANGE_AVATAR: 'CHANGE_AVATAR',

    FOUND_USERS: 'FOUND_USERS',
    CLEAR_FOUND_USERS: 'CLEAR_FOUND_USERS',

    SHOW_ADDUSER: 'SHOW_ADDUSER',
    HIDE_ADDUSER: 'HIDE_ADDUSER',
    SHOW_CREATEGROUP: 'SHOW_CREATEGROUP',
    HIDE_CREATEGROUP: 'HIDE_CREATEGROUP',
    INCLUDE_IN_NEW_GROUP: 'INCLUDE_IN_NEW_GROUP',
    EXCLUDE_FROM_NEW_GROUP: 'EXCLUDE_FROM_NEW_GROUP',

    SHOW_PROFILE: 'SHOW_PROFILE',
    HIDE_PROFILE: 'HIDE_PROFILE',

    SHOW_LOADER: 'SHOW_LOADER',
    HIDE_LOADER: 'HIDE_LOADER',

    CREATE_CHAT: 'CREATE_CHAT',
    OPEN_CHAT: 'OPEN_CHAT',
    LOAD_CHATS: 'LOAD_CHATS',

    ADD_ATTACHMENTS: 'ADD_ATTACHMENTS',
    DELETE_ATTACHMENT: 'DELETE_ATTACHMENT',
    RESET_ATTACHMENTS: 'RESET_ATTACHMENTS',
    ATTACHMENTS_UPLOADING: 'ATTACHMENTS_UPLOADING',

    SHOW_INPUT_POPUP: 'SHOW_INPUT_POPUP',
    HIDE_INPUT_POPUP: 'HIDE_INPUT_POPUP',

    SHOW_EMOJI: 'SHOW_EMOJI',
    HIDE_EMOJI: 'HIDE_EMOJI',

    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
    UPDATE_MESSAGE: 'UPDATE_MESSAGE',
    UPDATE_CHAT: 'UPDATE_CHAT',

    SHOW_FULL_SIZE_IMAGE: 'SHOW_FULL_SIZE_IMAGE',
    HIDE_FULL_SIZE_IMAGE: 'HIDE_FULL_SIZE_IMAGE',

    SHOW_WARNING: 'SHOW_WARNING',
    HIDE_WARNING: 'HIDE_WARNING',

    SET_FORWARD: 'SET_FORWARD',
    SET_REPLY: 'SET_REPLY',
    DELETE_FORWARD: 'DELETE_FORWARD',
    DELETE_REPLY: 'DELETE_REPLY',

    DESTRUCT_MESSAGE: 'DESTRUCT_MESSAGE',
    SET_SELF_DESTRUCT: 'SET_SELF_DESTRUCT',
    RESET_SELF_DESTRUCT: 'RESET_SELF_DESTRUCT',

    SHOW_CONTACTS_TO_FORWARD: 'SHOW_CONTACTS_TO_FORWARD',
    HIDE_CONTACTS_TO_FORWARD: 'HIDE_CONTACTS_TO_FORWARD'
};
