'use strict';

export default {
    FOUND_USERS: 'FOUND_USERS',

    HIDE_ADDUSER: 'HIDE_ADDUSER',
    HIDE_CREATEGROUP: 'HIDE_CREATEGROUP',
    HIDE_PROFILE: 'HIDE_PROFILE',

    SHOW_LOADER: 'SHOW_LOADER',
    HIDE_LOADER: 'HIDE_LOADER',

    CREATE_CHAT: 'CREATE_CHAT',
    OPEN_CHAT: 'OPEN_CHAT',

    CHANGE_AVATAR: 'CHANGE_AVATAR'
};
